
# 友链的写法示例
# links:
# - name: xaoxuu's blog
#   avatar: https://xaoxuu.com/assets/img/avatar.jpg
#   url: https://blog.xaoxuu.com

# 页脚社交信息的写法示例
social:
  - icon: fas fa-envelope
    url: mailto:neo.shilong.xu@gmail.com
  - icon: fab fa-github
    url: https://github.com/Lv-neo/Learn

# 博主信息的写法示例
# avatar: /Learn/img/me.jpg
# title: neo's blog
# motto: 下班？不存在的


# >> 主题配置 ---------------------------------------------------------------------

# 字体 在这里选好你需要的字体：https://fonts.google.com，然后在_defines.less中修改font_family。
google_fonts: 'Ubuntu|Ubuntu+Mono' # 多个字体中间用英文竖线隔开

# style: material    # 导航栏和标题栏背景是主题色
style: black        # 导航栏和标题栏背景是白色

# 导航栏
nav_menu:
  - name: 主页
    slug:
    icon: fas fa-home
    url: /
  # - name: 标签
  #   slug: tag
  #   icon: fas fa-bookmarks
  #   url: /tag
  - name: 博客
    slug: archives
    icon: fas fa-archive
    url: /archives/
  - name: 目录
    slug: list
    icon: fas fa-draw
    url: /index/

# 右边的小窗口，不想显示哪一项的注释掉对应的即可
widgets:
  # 博主信息区，是否显示个人头像、格言、社交信息等
  author:
    enable: true
    avatar: true # 是否显示头像，如果是，需要在主目录的config中写avatar的URL
    title: false # 是否显示博客名、头衔等等。如果是，需要在主目录的config中写title
    motto: false # 是否显示格言座右铭等等。如果是，需要在主目录的config中写motto
    social: true # 是否显示社交信息（内容同页脚的社交信息）如果是，需要在主目录的config中写social，支持icon和URL
  # 显示文章分类
  categories:
    enable: true
    icon: fas fa-folder-open
    title: "分类"
  # 显示文章标签
  tagcloud:
    enable: true
    icon: fas fa-tags
    title: "标签"
  # 显示网易云歌单
  music:
    enable: false
    icon: fas fa-headphones-alt
    title: "音乐"
    playlist_id: 746319661 # 歌单id
  # 显示友链，友链的内容写在主目录的config中
  links:
    enable: true
    icon: fas fa-handshake
    title: "友链"
    mailto: "me@xaoxuu.com" # 右边显示➕ ，点击给这个地址发送邮件添加友链
  # 显示目录（在文章中设置toc:false可以隐藏单篇文章的目录）
  toc:
    enable: true
    icon: fas fa-list
    title: "目录"


# 推荐文章
recommended_posts:
  autoDisplay: false # 自动在文章底部显示推荐文章，如果你使用Material-X主题，这里要设置为false。
  server: / # 后端推荐服务器地址
  timeoutInMillis: 10000 # 服务时长，超过此时长，则使用离线推荐模式
  excludePattern: []
  titleHtml: <h4>推荐文章</h4> #自定义标题
  internalLinks: 3 # 内部文章数量
  externalLinks: 2 # 外部文章数量
  fixedNumber: false


# Search
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less
less:
  compress: true
